# Basic
title: Evan Zou
subtitle: A slef blog for Jekyll
welcome_message: Hi I am Evan, nice to meet you all. Welcome to my blog.
description: Javascript follower.
creator: <a href="https://evanzew.github.io/">@EVAN</a>

url: 'https://evanzew.github.io/'

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
  title: Blog
  description: Visit blog

# Navigation buttons in the front page.
nav:
  - {
      title: Projects,
      description: My Projects,
      url: 'https://github.com/evanzew',
    }
  # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: 'page/:num/'

# Comment
comment:
  disqus: Evan Zou
  # duoshuo:

# Social
social:
  weibo: 眼睛大啊大
  github: evanzew
  #   twitter: onevcat
  #   gplus: 107108267983477358170
  mail: 137020260@qq.com

# Google Analytics
ga:
  # id: your_ga_id
  # host: your_host
